export const SEED = [
  {
    id: "1",
    name: "Cuisiner",
    description: "Crêpes maison avec sirop d'érable",
    durationHour: 1,
    durationMinute: 30,
    category: "Breakfast",
  },
  {
    id: "2",
    name: "Manger",
    description: "Poulet, bacon, laitue et tomate",
    durationHour: 0,
    durationMinute: 10,
    category: "Lunch",
  },
  {
    id: "3",
    name: "Pâté chinois",
    description: "Bœuf, maïs et purée de pommes de terre",
    durationHour: 1,
    durationMinute: 10,
    category: "Dinner",
  },
  {
    id: "4",
    name: "mop",
    description: "Faire la mop",
    durationHour: 0,
    durationMinute: 30,
    category: "Lunch",
  },
  {
    id: "5",
    name: "rdv_coiffure",
    description: "salon nivea",
    durationHour: 1,
    durationMinute: 10,
    category: "Dinner",
  },
  {
    id: "6",
    name: "Dormir",
    description: "bof",
    durationHour: 8,
    durationMinute: 10,
    category: "Lunch",
  },
  {
    id: "7",
    name: "charger_phone",
    description: "charger le telephone avant de sortir",
    durationHour: 0,
    durationMinute: 10,
    category: "Dinner",
  },
  {
    id: "8",
    name: "Club ",
    description: "danser",
    durationHour: 3,
    durationMinute: 30,
    category: "Lunch",
  },
  {
    id: "9",
    name: "Pâté chien",
    description: "Bœuf, maïs et purée de pommes de terre",
    durationHour: 0,
    durationMinute: 10,
    category: "Dinner",
  },
  {
    id: "10",
    name: "Club sandwich",
    description: "Poulet, bacon, laitue et tomate",
    durationHour: 0,
    durationMinute: 15,
    category: "Lunch",
  },
  {
    id: "11",
    name: "Pâté chinois",
    description: "Bœuf, maïs et purée de pommes de terre",
    durationHour: 1,
    durationMinute: 10,
    category: "Dinner",
  },
];
